/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Service_Management;

/**
 *
 * @author kd
 */
public class service_details extends javax.swing.JFrame {

    /**
     * Creates new form service_details
     */
    public service_details() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jTextField2 = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jTextField3 = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jTextField4 = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox<>();
        jLabel7 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jList1 = new javax.swing.JList<>();
        jLabel8 = new javax.swing.JLabel();
        jTextField5 = new javax.swing.JTextField();
        jToggleButton1 = new javax.swing.JToggleButton();
        jLabel9 = new javax.swing.JLabel();
        jTextField6 = new javax.swing.JTextField();
        jToggleButton2 = new javax.swing.JToggleButton();
        jLabel10 = new javax.swing.JLabel();
        jRadioButton1 = new javax.swing.JRadioButton();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jLabel1.setText("CUSTOMER  NAME :");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(30, 40, 140, 40);
        getContentPane().add(jTextField1);
        jTextField1.setBounds(170, 40, 270, 40);

        jLabel2.setText("CUSTOMER ID:");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(515, 40, 110, 40);
        getContentPane().add(jTextField2);
        jTextField2.setBounds(625, 41, 270, 40);

        jLabel3.setText("VEHICLE NO:");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(30, 133, 128, 37);
        getContentPane().add(jTextField3);
        jTextField3.setBounds(170, 129, 270, 46);

        jLabel4.setText("CONTACT NO:");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(515, 128, 102, 46);

        jTextField4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField4ActionPerformed(evt);
            }
        });
        getContentPane().add(jTextField4);
        jTextField4.setBounds(630, 140, 220, 43);

        jLabel5.setText("VEHICLE DETAILS :");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(30, 211, 128, 44);

        jLabel6.setText("COMPANY :");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(30, 287, 128, 44);

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "TVS", "BAJAJ", "HERO", "HONDA", "KTM", "ROYAL ENFIELD", "YAMAHA", "OTHER" }));
        jComboBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox1ActionPerformed(evt);
            }
        });
        getContentPane().add(jComboBox1);
        jComboBox1.setBounds(220, 287, 99, 44);

        jLabel7.setText("MODEL :");
        getContentPane().add(jLabel7);
        jLabel7.setBounds(515, 287, 102, 56);

        jList1.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane1.setViewportView(jList1);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(671, 287, 54, 56);

        jLabel8.setText("LAST SERVICE :");
        getContentPane().add(jLabel8);
        jLabel8.setBounds(30, 378, 157, 45);

        jTextField5.setText("DD/MM/YYYY");
        getContentPane().add(jTextField5);
        jTextField5.setBounds(220, 379, 178, 44);

        jToggleButton1.setText("OIL  CHANGE");
        getContentPane().add(jToggleButton1);
        jToggleButton1.setBounds(520, 470, 101, 48);

        jLabel9.setText("SPECIFIC PART SERVICE");
        getContentPane().add(jLabel9);
        jLabel9.setBounds(515, 378, 157, 44);

        jTextField6.setText("PART NAME");
        getContentPane().add(jTextField6);
        jTextField6.setBounds(684, 379, 220, 44);

        jToggleButton2.setText("INSTANT SERVICE");
        getContentPane().add(jToggleButton2);
        jToggleButton2.setBounds(690, 470, 141, 48);

        jLabel10.setText("RATE YOUR LAST SERVICE");
        getContentPane().add(jLabel10);
        jLabel10.setBounds(30, 450, 206, 48);

        jRadioButton1.setText("SATISFACTORY");
        jRadioButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jRadioButton1);
        jRadioButton1.setBounds(280, 470, 128, 24);

        jButton1.setText("SUBMIT");
        getContentPane().add(jButton1);
        jButton1.setBounds(40, 569, 140, 50);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextField4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField4ActionPerformed

    private void jComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox1ActionPerformed
        if(jComboBox1.getText()=="TVS")        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox1ActionPerformed

    private void jRadioButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jRadioButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(service_details.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(service_details.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(service_details.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(service_details.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new service_details().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JList<String> jList1;
    private javax.swing.JRadioButton jRadioButton1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JTextField jTextField5;
    private javax.swing.JTextField jTextField6;
    private javax.swing.JToggleButton jToggleButton1;
    private javax.swing.JToggleButton jToggleButton2;
    // End of variables declaration//GEN-END:variables
}
